### ISSUE TITLE
migrations are still using South

### ISSUE THREAD

**Issue by nim65s** [django-blog-zinnia/zinnia-wysiwyg-tinymce#4]
Hello,

Running a `manage.py migrate` with django 1.8 does not apply the migration provided here, because it seems to have been generated with South.

**Comment by ZuluPro** [comment]
@nim65s I'm fixing it here: #5

**Comment by Fantomas42** [comment]
Fixed in zinnia-wysiwyg-tinymce v1.3

**Comment by nim65s** [comment]
Thanks :)
