### ISSUE TITLE
No Reverse for 'tinymce-js'

### ISSUE THREAD

**Issue by Fantomas42** [django-blog-zinnia/zinnia-wysiwyg-tinymce#6]
As reported by @dilatgh

zinnia-wysiwig-tinymce doesn't work. "tinymce-js" URL name and its view textareas_js  don't exist in django-tinymce anymore: https://github.com/aljosa/django-tinymce/commit/1535f5c33544c4ac49d397ec14e2ec88e177587d#diff-99f82678a1ffa0a31e0576ec938419c9

**Comment by ghachey** [comment]
I see this is closed. Is it fixed in 'develop'? I get the error when installing latest from pip.
