### ISSUE TITLE
Cut new release to fix URL error

### ISSUE THREAD

**Issue by ghachey** [django-blog-zinnia/zinnia-wysiwyg-tinymce#8]
Latest from pip fails with:
```
from django.conf.urls import patterns
    ImportError: cannot import name 'patterns'
```
I see this was addressed in b849ac823a9308ca1b427b8a715be83df241c52b but the latest installed by pip does not contain this change and still fails. Any chance to get a release for this fix?

**Comment by tundebabzy** [comment]
+1. I have considered pip installing from the github repo but I chose to manually copy and paste the changed files.

**Comment by Fantomas42** [comment]
The new release was not published because of the latest versions of django-tinymce who are breaking all the project.

I working on a solution.

**Comment by Fantomas42** [comment]
zinnia-wysiwyg-tinymce v1.4 published on pypi.
