### ISSUE TITLE
django-tinymce 2.2 not support django 1.10

### ISSUE THREAD

**Issue by jaumemateu** [django-blog-zinnia/zinnia-wysiwyg-tinymce#9]
Since django-tinymce has downgraded to 2.2 the package does not work with django 1.10. Maybe could be updated to 2.6 but considering #6 and #7.

**Comment by Fantomas42** [comment]
Hello,

I don't see what is your idea. Could you be more explicit ?

Regards

**Comment by gabn88** [comment]
If you want to use zinnia-wysiwyg-tinymce you are stuck with django < 1.9, which is not supported anymore. In other words, this package is obsolete.
